apiVersion: v1
kind: Service
metadata:
  name: prometheus-test
  namespace: monitoring
  annotations:
   cloud.google.com/load-balancer-type: Internal
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: prometheus-server
